name: event_manager2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cloud_firestore: ^5.4.5
  firebase_auth: ^5.3.2
  firebase_core: ^3.6.0
  firebase_ui_auth: ^1.16.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.10.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.4+1
  go_router: ^14.4.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  intl: any
  localstore: ^1.4.0
  provider: ^6.1.2
  syncfusion_flutter_calendar: ^27.1.57

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
