// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPo1LgtXHh058peMs5kRTs4kGg07uvHP0',
    appId: '1:103536848583:web:bb1516ccd1367c766658e2',
    messagingSenderId: '103536848583',
    projectId: 'even-manager-d315f',
    authDomain: 'even-manager-d315f.firebaseapp.com',
    storageBucket: 'even-manager-d315f.firebasestorage.app',
    measurementId: 'G-N5VXXFQJ8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeYgJr_1VVsjD2pw_vwr9OfNMoo48sJGo',
    appId: '1:103536848583:android:5b70f826e28fb8dd6658e2',
    messagingSenderId: '103536848583',
    projectId: 'even-manager-d315f',
    storageBucket: 'even-manager-d315f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPWeqiAVXBc-6hfeptm6OmHLHQ1D69CU4',
    appId: '1:103536848583:ios:dd5f1d74655ff6536658e2',
    messagingSenderId: '103536848583',
    projectId: 'even-manager-d315f',
    storageBucket: 'even-manager-d315f.firebasestorage.app',
    iosBundleId: 'com.example.eventManager2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPWeqiAVXBc-6hfeptm6OmHLHQ1D69CU4',
    appId: '1:103536848583:ios:dd5f1d74655ff6536658e2',
    messagingSenderId: '103536848583',
    projectId: 'even-manager-d315f',
    storageBucket: 'even-manager-d315f.firebasestorage.app',
    iosBundleId: 'com.example.eventManager2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPo1LgtXHh058peMs5kRTs4kGg07uvHP0',
    appId: '1:103536848583:web:54daed9d0be4df596658e2',
    messagingSenderId: '103536848583',
    projectId: 'even-manager-d315f',
    authDomain: 'even-manager-d315f.firebaseapp.com',
    storageBucket: 'even-manager-d315f.firebasestorage.app',
    measurementId: 'G-1C6X1PKD2F',
  );
}


